### PR TITLE
2 small fixes

### PR DESCRIPTION
**Pull request by dionoid**
fix for passing fields in ByGameName API calls
fix for supporting Image "side" property

### CODE REVIEW

**Comment by nfMalde** [comment]
Merged - Will be released soon as 1.1.x Version. Thanks for the PR👍

**Comment by nfMalde** [comment]
Released in Version [TheGamesDBApiWrapper 1.1.x](https://www.nuget.org/packages/TheGamesDBApiWrapper/1.1.1)

**Comment by dionoid** [comment]
Wow, thanks for the quick merge and release!

**Comment by nfMalde** [comment]
No problem! Glad the API Wrapper helps :-)

**Pull request merged**
